module.exports = Keys =
  uppercase:
    alt: 'ALT'
    cmd: 'CMD'
    ctrl: 'CTRL'
    meta: 'META'
    shift: 'SHIFT'
    space: 'SPC'
    tab: 'TAB'
    'super': 'SUPER'
    win: 'WIN'
    escape: 'ESC'
    esc: 'ESC'
    backspace: 'BACKSPACE'
    del: 'DEL'
    delete: 'DEL'
    enter: 'ENTER'
    'return': 'RETURN'
    up: 'UP'
    down: 'DOWN'
    left: 'LEFT'
    right: 'RIGHT'
  short:
    alt: 'A'
    cmd: 'D'
    ctrl: 'C'
    meta: 'M'
    shift: 'S'
  symbols:
    alt: '\u2325'
    cmd: '\u2318'
    ctrl: '\u2303'
    meta: '\u2325'
    shift: '\u21E7'
    enter: '\u23CE'
    'return': '\u23CE'
    tab: '\u21B9'
    backspace: '\u232B'
    escape: '\u238B'
    esc: '\u238B'
    up: '\u2191'
    down: '\u2193'
    left: '\u2190'
    right: '\u2192'
